/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanaInicio;
import clavedicotomica.leerJson;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import clavedicotomica.Arbol;
import clavedicotomica.TablaDispersion;
import clavedicotomica.GraficoArbol;
import clavedicotomica.Nodo;

/**
 * Clase principal que representa la ventana de inicio de la aplicación.
 * Esta ventana permite desde cargar el Json, mostrar el árbol de la clave dicotómica,
 * determinar una especie y buscar una especie en el árbol.
 */

public class Inicio extends javax.swing.JFrame {
    private Arbol arbol; // Árbol para la clave dicotómica
    private TablaDispersion tabla; // Tabla de dispersión para las especies
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargarJson = new javax.swing.JButton();
        Grafo = new javax.swing.JButton();
        determinarEspecie = new javax.swing.JButton();
        buscarEspecie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cargarJson.setText("Cargar Json");
        cargarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarJsonActionPerformed(evt);
            }
        });

        Grafo.setText("Mostrar Grafo");
        Grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrafoActionPerformed(evt);
            }
        });

        determinarEspecie.setText("Determinar especie");
        determinarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                determinarEspecieActionPerformed(evt);
            }
        });

        buscarEspecie.setText("Buscar especie");
        buscarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEspecieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(determinarEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(cargarJson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grafo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarJson, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grafo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(determinarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrafoActionPerformed
        if (arbol != null) {
            GraficoArbol.mostrarArbol(arbol.getRaiz());
        } else {
            JOptionPane.showMessageDialog(this, "Primero carga un archivo JSON.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    

    }//GEN-LAST:event_GrafoActionPerformed

    private void cargarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarJsonActionPerformed
          
            // Crear una instancia de JFileChooser
        JFileChooser fileChooser = new JFileChooser();

        // Mostrar el diálogo para abrir un archivo
        int seleccion = fileChooser.showOpenDialog(null);

        // Verificar si el usuario seleccionó un archivo
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // Obtener el archivo seleccionado
            File archivoSeleccionado = fileChooser.getSelectedFile();

            // Obtener la extensión del archivo
            String nombreArchivo = archivoSeleccionado.getName();
            String extension = "";

            // Obtener la extensión del archivo
            int i = nombreArchivo.lastIndexOf('.');
            if (i > 0) {
                extension = nombreArchivo.substring(i + 1).toLowerCase();
            }

            // Verificar si la extensión es "json"
            if ("json".equals(extension)) {
                // Mostrar la ruta del archivo seleccionado
                JOptionPane.showMessageDialog(this, "Archivo seleccionado: " + archivoSeleccionado.getAbsolutePath(), "Cargar Json", JOptionPane.INFORMATION_MESSAGE);

                // Construir el árbol y la tabla de dispersión
                tabla = new TablaDispersion();
                arbol = leerJson.construirArbol(archivoSeleccionado, tabla);

                if (arbol != null) {
                    JOptionPane.showMessageDialog(this, "Árbol y tabla de dispersión construidos correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al construir el árbol.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Mostrar un mensaje de error si el archivo no es JSON
                JOptionPane.showMessageDialog(this, "El archivo seleccionado no es un archivo JSON.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_cargarJsonActionPerformed

    private void determinarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_determinarEspecieActionPerformed
        if (arbol == null) {
        JOptionPane.showMessageDialog(this, "Primero carga un archivo JSON.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Comenzar desde la raíz
    Nodo nodoActual = arbol.getRaiz();
    
    // Mientras no se llegue a una hoja (especie)
    while (nodoActual != null && nodoActual.getEspecie() == null) {
        // Mostrar la pregunta actual
        int respuesta = JOptionPane.showConfirmDialog(
            this,
            nodoActual.getPregunta(),
            "Determinar Especie",
            JOptionPane.YES_NO_OPTION
        );
        
        // Avanzar según la respuesta
        if (respuesta == JOptionPane.YES_OPTION) {
            nodoActual = nodoActual.getSi();
        } else {
            nodoActual = nodoActual.getNo();
        }
        
        // Verificar si se llegó a un nodo nulo (camino incompleto)
        if (nodoActual == null) {
            JOptionPane.showMessageDialog(
                this,
                "No se pudo determinar la especie. El árbol está incompleto.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
    }
    
    // Mostrar la especie encontrada
    if (nodoActual != null && nodoActual.getEspecie() != null) {
        JOptionPane.showMessageDialog(
            this,
            "La especie determinada es: " + nodoActual.getEspecie(),
            "Especie Encontrada",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
            this,
            "No se pudo determinar la especie.",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }

    }//GEN-LAST:event_determinarEspecieActionPerformed

    private void buscarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEspecieActionPerformed
    if (arbol == null || tabla == null) {
        JOptionPane.showMessageDialog(this, "Primero carga un archivo JSON.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Solicitar el nombre de la especie
    String nombreEspecie = JOptionPane.showInputDialog(this, "Introduce el nombre de la especie a buscar:", "Buscar Especie", JOptionPane.QUESTION_MESSAGE);
    
    if (nombreEspecie == null || nombreEspecie.trim().isEmpty()) {
        return; // Usuario canceló o no ingresó nada
    }
    
    // Capitalizar la primera letra del nombre de la especie
    nombreEspecie = capitalizarPrimeraLetra(nombreEspecie);
    
    // Preguntar al usuario qué método quiere usar
    String[] opciones = {"Buscar por Hash", "Buscar por Recorrido del Árbol"};
    int seleccion = JOptionPane.showOptionDialog(
        this,
        "Selecciona el método de búsqueda:",
        "Método de Búsqueda",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        opciones,
        opciones[0]
    );
    
    if (seleccion == 0) {
        // Buscar por hash
        buscarPorHash(nombreEspecie);
    } else if (seleccion == 1) {
        // Buscar por recorrido del árbol
        buscarPorRecorrido(nombreEspecie);
    }
}

// Método para capitalizar la primera letra de un String
private String capitalizarPrimeraLetra(String str) {
    if (str == null || str.isEmpty()) {
        return str;
    }
    return str.substring(0, 1).toUpperCase() + str.substring(1).toLowerCase();
}

/**
 * Busca una especie usando la tabla de dispersión (hash).
 */
private void buscarPorHash(String nombreEspecie) {
    // Medir tiempo de inicio
    long tiempoInicio = System.nanoTime();
    
    // Realizar la búsqueda
    Nodo nodoEspecie = tabla.buscar(nombreEspecie);
    
    // Medir tiempo de fin
    long tiempoFin = System.nanoTime();
    
    // Calcular tiempo transcurrido en nanosegundos y convertir a milisegundos para mejor legibilidad
    long tiempoTranscurrido = tiempoFin - tiempoInicio;
    double tiempoEnMilisegundos = tiempoTranscurrido / 1000000.0;
    
    if (nodoEspecie != null && nombreEspecie.equals(nodoEspecie.getEspecie())) {
        JOptionPane.showMessageDialog(
            this,
            "Especie encontrada en la tabla de hash: " + nombreEspecie + "\n\n" +
            "Tiempo de búsqueda: " + tiempoEnMilisegundos + " milisegundos",
            "Especie Encontrada",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        // Mostrar el camino de preguntas hasta esta especie
        mostrarCaminoHastaEspecie(nombreEspecie);
    } else {
        JOptionPane.showMessageDialog(
            this,
            "La especie '" + nombreEspecie + "' no se encontró en la tabla de hash.\n\n" +
            "Tiempo de búsqueda: " + tiempoEnMilisegundos + " milisegundos",
            "Especie No Encontrada",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

/**
 * Busca una especie recorriendo el árbol.
 */
private void buscarPorRecorrido(String nombreEspecie) {
    // Estructura para almacenar el camino
    StringBuilder camino = new StringBuilder();
    
    // Medir tiempo de inicio
    long tiempoInicio = System.nanoTime();
    
    // Buscar la especie en el árbol mediante un recorrido
    boolean encontrada = buscarEspecieEnArbol(arbol.getRaiz(), nombreEspecie, camino);
    
    // Medir tiempo de fin
    long tiempoFin = System.nanoTime();
    
    // Calcular tiempo transcurrido en nanosegundos y convertir a milisegundos para mejor legibilidad
    long tiempoTranscurrido = tiempoFin - tiempoInicio;
    double tiempoEnMilisegundos = tiempoTranscurrido / 1000000.0;
    
    if (encontrada) {
        JOptionPane.showMessageDialog(
            this,
            "Especie encontrada por recorrido del árbol: " + nombreEspecie + "\n\n" +
            "Camino para llegar a esta especie:\n" + camino.toString() + "\n\n" +
            "Tiempo de búsqueda: " + tiempoEnMilisegundos + " milisegundos",
            "Especie Encontrada",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
            this,
            "La especie '" + nombreEspecie + "' no se encontró en el árbol.\n\n" +
            "Tiempo de búsqueda: " + tiempoEnMilisegundos + " milisegundos",
            "Especie No Encontrada",
            JOptionPane.ERROR_MESSAGE
        );
    }
}

/**
 * Busca una especie en el árbol y construye el camino de preguntas hasta ella.
 */
private boolean buscarEspecieEnArbol(Nodo nodo, String nombreEspecie, StringBuilder camino) {
    if (nodo == null) {
        return false;
    }
    
    // Si encontramos la especie
    if (nodo.getEspecie() != null && nodo.getEspecie().equals(nombreEspecie)) {
        return true;
    }
    
    // Si no es una hoja, buscar en sus hijos
    if (nodo.getPregunta() != null) {
        // Intentar por el camino SI
        camino.append("Pregunta: ").append(nodo.getPregunta()).append(" → Respuesta: Sí\n");
        if (buscarEspecieEnArbol(nodo.getSi(), nombreEspecie, camino)) {
            return true;
        } else {
            // Quitar la última pregunta si no encontramos por este camino
            int ultimaLinea = camino.lastIndexOf("Pregunta: ");
            if (ultimaLinea >= 0) {
                camino.delete(ultimaLinea, camino.length());
            }
            
            // Intentar por el camino NO
            camino.append("Pregunta: ").append(nodo.getPregunta()).append(" → Respuesta: No\n");
            if (buscarEspecieEnArbol(nodo.getNo(), nombreEspecie, camino)) {
                return true;
            } else {
                // Quitar la última pregunta si no encontramos por este camino
                ultimaLinea = camino.lastIndexOf("Pregunta: ");
                if (ultimaLinea >= 0) {
                    camino.delete(ultimaLinea, camino.length());
                }
                return false;
            }
        }
    }
    
    return false;
}

/**
 * Muestra el camino de preguntas hasta una especie usando el árbol.
 */
private void mostrarCaminoHastaEspecie(String nombreEspecie) {
    StringBuilder camino = new StringBuilder();
    
    // Medir tiempo de inicio
    long tiempoInicio = System.nanoTime();
    
    // Buscar el camino de preguntas
    boolean encontrado = buscarEspecieEnArbol(arbol.getRaiz(), nombreEspecie, camino);
    
    // Medir tiempo de fin
    long tiempoFin = System.nanoTime();
    
    // Calcular tiempo transcurrido
    long tiempoTranscurrido = tiempoFin - tiempoInicio;
    double tiempoEnMilisegundos = tiempoTranscurrido / 1000000.0;
    
    if (encontrado) {
        JOptionPane.showMessageDialog(
            this,
            "Camino para llegar a esta especie:\n" + camino.toString() + "\n\n" +
            "Tiempo de búsqueda del camino: " + tiempoEnMilisegundos + " milisegundos",
            "Camino de Preguntas",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        JOptionPane.showMessageDialog(
            this,
            "No se pudo determinar el camino de preguntas.\n\n" +
            "Tiempo de búsqueda: " + tiempoEnMilisegundos + " milisegundos",
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_buscarEspecieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Grafo;
    private javax.swing.JButton buscarEspecie;
    private javax.swing.JButton cargarJson;
    private javax.swing.JButton determinarEspecie;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
